### ISSUE TITLE
デザイン２パターンの方針決め

### ISSUE THREAD

**Issue by denshidenki** [denshidenki/mao-seminar#1]
仮タイトル付与
TOPページに置こうと思っている各メニューとWORKS画像の構成案を２パターン作って比較したいと思います。

TODO
------------------------------------
- [ ] パターンA
- [x] パターンB

**Comment by denshidenki** [comment]
TOPページに置こうと思っている各メニューとWORKS画像の構成案を２パターン作って比較したいと思います。

TODO
------------------------------------------------
- [ ] パターンA
- [x] パターンB

**Comment by denshidenki** [comment]
マークダウンは**Previewタグ**で確認できます。

**Comment by kikou-isseki** [comment]
ホソタニからのコメントです
